[project]
name = "f1bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "bs4>=0.0.2",
    "discord>=2.3.2",
    "dotenv>=0.9.9",
]
